/**
 * @file This script is auto-generated by create-nitro-module and should not be edited.
 *
 * @description Post-codegen patches:
 * - Android: strip `margelo/nitro/` from OnLoad.cpp and rewrite view-manager wildcard imports.
 * - iOS: seed HybridView `_props` so Fabric's RCTViewComponentView assertion does not abort.
 *
 * @module create-nitro-module
 */
const path = require('node:path')
const { writeFile, readFile, readdir } = require('node:fs/promises')

const viewManagerDir = path.join(
  process.cwd(),
  'nitrogen/generated/android/kotlin/com/margelo/nitro/nitrogooglesignin/views'
)

const updateViewManagerFiles = async (file) => {
  const viewManagerFile = path.join(viewManagerDir, file)

  const viewManagerStr = await readFile(viewManagerFile, { encoding: 'utf8' })
  await writeFile(
    viewManagerFile,
    viewManagerStr.replace(
      /com\.margelo\.nitro\.nitrogooglesignin\.\*/g,
      'com.nitrogooglesignin.*'
    )
  )
}

const androidWorkaround = async () => {
  const androidOnLoadFile = path.join(
    process.cwd(),
    'nitrogen/generated/android',
    'NitroGoogleSigninOnLoad.cpp'
  )

  const viewManagerDirEntries = await readdir(viewManagerDir)
  const viewManagerFiles = viewManagerDirEntries.filter((file) =>
    file.endsWith('Manager.kt')
  )
  const res = await Promise.allSettled(
    viewManagerFiles.map(updateViewManagerFiles)
  )

  if (res.some((r) => r.status === 'rejected')) {
    throw new Error('Error updating view manager files: ' + JSON.stringify(res))
  }

  const str = await readFile(androidOnLoadFile, { encoding: 'utf8' })
  await writeFile(androidOnLoadFile, str.replace(/margelo\/nitro\//g, ''))
}

const PROPS_SEED =
  '    _props = HybridGoogleSignInButtonShadowNode::defaultSharedProps();\n'

/** Nitrogen's HybridView `-init` never seeds `_props`, so Fabric's RCTAssert in
 * `-[RCTViewComponentView updateProps:oldProps:]` aborts on first mount. */
const seedIosHybridViewProps = async () => {
  const iosComponentMm = path.join(
    process.cwd(),
    'nitrogen/generated/ios/c++/views',
    'HybridGoogleSignInButtonComponent.mm'
  )
  const str = await readFile(iosComponentMm, { encoding: 'utf8' })
  if (str.includes('HybridGoogleSignInButtonShadowNode::defaultSharedProps()')) {
    return
  }

  const needle =
    '  if (self = [super init]) {\n    std::shared_ptr<HybridGoogleSignInButtonSpec> hybridView'
  if (!str.includes(needle)) {
    throw new Error(
      'HybridGoogleSignInButtonComponent.mm init() did not match the nitrogen template'
    )
  }

  await writeFile(
    iosComponentMm,
    str.replace(
      needle,
      `  if (self = [super init]) {\n${PROPS_SEED}    std::shared_ptr<HybridGoogleSignInButtonSpec> hybridView`
    )
  )
}

Promise.all([androidWorkaround(), seedIosHybridViewProps()])
